### PR TITLE
Pause for an extra 60 secs after abuse limit errors before retrying

### LINKED ISSUE #28: Crash with abuse rate limits
After having migrated ~20 milestones & ~10 issues, the program crashed on an issue creation request, with the following error message:

```
Error: {"message":"You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.","documentation_url":"https://developer.github.com/v3/#abuse-rate-limits"}
```

Reading [this section](https://developer.github.com/v3/#abuse-rate-limits) & [this section](https://developer.github.com/v3/guides/best-practices-for-integrators/#dealing-with-abuse-rate-limits) from the official docs, I guess the problem comes from performing more than 1 request per second.

I'd say this program doesn't take precautions in term of github rate abuse limits, but I'm really puzzled by the fact that the README mentions a successful 300 issues migration

### PR DESCRIPTION
**Pull request by akaihola**
Fixes #28.

### CODE REVIEW

**Comment by mattip** [comment]
Cool. You may want to raise the 60 seconds to 15 minutes?

**Comment by mattip** [comment]
Also - the unconditional catches on line 308 and 329 in `src/index.ts` means that the script will continue on happily processing when throttling errors happen, no? Does there need to be a retry mechanism or does throttling automatically retry?

**Comment by mahalel** [comment]
Hey, I've just tested this and it does seem that the script will keep processing when throttling errors happen still. 
Unfortunately I don't really know TypeScript to suggest a fix.

**Comment by akaihola** [comment]
> Cool. You may want to raise the 60 seconds to 15 minutes?

The problem with that is that if 15 minutes isn't sufficient, it will sleep for another 15 minutes which probably is almost 15 minutes too much. I did try and think of a way to do a 15-minute sleep followed by as many 1-minute sleeps as necessary, but couldn't think of a simple way to achieve that.

According to our tests, the abuse limit lock gets released in 20 to 23 minutes.

>the script will continue on happily processing when throttling errors happen

With this patch, the script should keep retrying every 65 seconds when it receives either an abuse limit error or a rate limit error response. When the request eventually gets through, it will continue processing the next request as if nothing unusual happened.

This is intentional and the point of the patch – we want to leave the script running and have it complete with exactly the same end result as would have achieved if no abuse/throttling errors were received.

I feel I don't entirely understand your concerns @mattip & @mahalel, could you clarify?

**Comment by mattip** [comment]
My concerns were based on misunderstanding how the throttling works. Thanks for the explanation. So a retry does not reset the lock timeout? That is good to know.

**Comment by larstiq** [comment]
Perhaps the behavior would be more clearly telegraphed if the PR was titled `Pause for an extra 60 secs after abuse limit errors before retrying`, rather than `Stop` which sounds final (to me).

**Review by spruce — APPROVED** [review]

**Pull request merged**
